services:
  reverse-proxy:
    image: traefik:v3.3
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --accesslog=true
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1 # temporaire, à changer en mode global
      placement:
        constraints:
          - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # Utilisateurs
  utilisateurs_web:
    build:
      context: ./services/utilisateurs
    image: utilisateurs_web_image:latest
    volumes:
      - ./services/utilisateurs/index.php:/var/www/html/index.php
    ports:
      - "8081:80"
    networks:
      - traefik-public
      - app-utilisateurs
    depends_on:
      - utilisateurs_db
      - utilisateurs_redis
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.utilisateurs.rule=Host(`utilisateurs.localhost`)"
      - "traefik.http.services.utilisateurs.loadbalancer.server.port=80"

  utilisateurs_db:
    image: mysql:latest
    container_name: utilisateurs_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_db
    networks:
      - app-utilisateurs
    volumes:
      - utilisateurs_db_data:/var/lib/mysql

  utilisateurs_redis:
    image: redis:latest
    container_name: utilisateurs_redis
    networks:
      - app-utilisateurs
    ports:
      - "6379:6379"

  # Cluster Swarm
  clusterswarm_web:
    build:
      context: ./services/clusterswarm
    image: clusterswarm_web_image:latest
    volumes:
      - ./services/clusterswarm/index.php:/var/www/html/index.php
    ports:
      - "8082:80"
    networks:
      - traefik-public
      - app-clusterswarm
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.cluster_swarm.rule=Host(`clusterswarm.localhost`)"
      - "traefik.http.services.cluster_swarm.loadbalancer.server.port=80"
  
  fortune_web:
    build:
      context: ./services/fortune
    image: fortune_web_image:latest
    volumes:
      - ./services/fortune/index.php:/var/www/html/index.php
    ports:
      - "8083:80"
    networks:
      - traefik-public
      - app-fortune
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.fortune.rule=Host(`fortune.localhost`)"
      - "traefik.http.services.fortune.loadbalancer.server.port=80"

networks:
  traefik-public:
    external: true
  app-utilisateurs:
    external: true
  app-clusterswarm:
    external: true
  app-fortune:
    external: true
  # app-flask:
  #   external: true
  # ...

volumes:
  utilisateurs_db_data:
    external: false