version: '3.7'

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmmode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - traefik-public
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      placement:
        constraints: [node.role == manager]

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`nginx.localhost.com`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    networks:
      - traefik-public

  php-app:
    image: php:7.4-fpm
    ports:
      - "8082:80"
    volumes:
      - ./php-app:/usr/src/myapp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpapp.rule=Host(`phpapp.localhost.com`)"
      - "traefik.http.services.phpapp.loadbalancer.server.port=80"
    networks:
      - traefik-public

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: phpappdb
      MYSQL_USER: phpappuser
      MYSQL_PASSWORD: phpapppass
    ports:
      - "3306:3306"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
