version: "3.9"
services:
  traefik:
    image: traefik:v2.10
    command:
      - --configFile=/etc/traefik/traefik.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml
    networks:
      - traefik-public
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
    ports:
      - 80:80
      - 443:443
      - 8080:8080
networks:
  traefik-public:
    external: true
