services:

  reverse-proxy:
    image: traefik:v3.3
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --accesslog=true
    ports:
      - "80:80"
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1 # temporaire, à changer en mode global
      placement:
        constraints:
          - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  utilisateurs_db:
    image: mysql:latest
    container_name: utilisateurs_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_db
    networks:
      - traefik-public
    volumes:
      - utilisateurs_db_data:/var/lib/mysql

  utilisateurs_web:
    build:
      context: ./services/utilisateurs
    image: utilisateurs_web_image:latest
    volumes:
      - ./services/utilisateurs/index.php:/var/www/html/index.php
    ports:
      - "8081:80"
    networks:
      - traefik-public
    depends_on:
      - utilisateurs_db
      - utilisateurs_redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.utilisateurs.rule=Host(`utilisateurs.localhost`)"
      - "traefik.http.services.utilisateurs.loadbalancer.server.port=80"

  utilisateurs_redis:
    image: redis:latest
    container_name: utilisateurs_redis
    networks:
      - traefik-public
    ports:
      - "6379:6379"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redis.rule=Host(`redis.localhost`)"
      - "traefik.http.services.redis.loadbalancer.server.port=6379"

networks:
  traefik-public:
    external: true

volumes:
  utilisateurs_db_data:
    external: false