entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: true # Désactiver en production et utiliser une authentification

providers:
  docker:
    swarmMode: true
    exposedByDefault: false

log:
  level: INFO
