services:
  web:
    build: .
    ports:
      - "8084:80"
    environment:
      - FLASK_ENV=development
    depends_on:
      - flask_redis
    volumes:
      - .:/app

  flask_redis:
    image: "redis:latest"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
