version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:8000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: "redis:latest"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
